version: '3'

volumes: 
  pgdata: {}
  pgdata_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: codebase_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: 
      - ./.envs/.postgres
    depends_on: 
      - postgres
    command: /start


  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: codebase_postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - pgdata_backups:/backups
    env_file: 
      - ./.envs/.postgres